services:
  backend_prod:
    build:
      context: ./RZHDBack
      dockerfile: Dockerfile
    container_name: backend_prod
    environment:
      APP_ENV: prod
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8080:8080"
    networks:
      - monsieur-kotov-system
    volumes:
      - ./RZHDBack/config:/app/config
      - ./RZHDBack/temp:/app/temp
      - ./RZHDBack/data:/app/data
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
    profiles:
      - dev
      - prod


  frontend_dev:
    build:
      context: ./RZHDFront
      dockerfile: Dockerfile.dev
    depends_on:
      backend_prod:
        condition: service_started
    container_name: ip_kotov_frontend_site_dev
    ports:
      - "80:80"
    networks:
      - monsieur-kotov-system
    profiles:
      - dev

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - monsieur-kotov-system
    restart: unless-stopped

  frontend_prod:
    build:
      context: ./RZHDFront
      dockerfile: Dockerfile
    depends_on:
      backend_prod:
        condition: service_started
    container_name: ip_kotov_frontend_site
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - monsieur-kotov-system
    profiles:
      - prod

networks:
  monsieur-kotov-system:
    driver: bridge