events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;

    server {
        listen 80;
        server_name tkremont58.ru;
        return 301 https://$host$request_uri;

        location = /robots.txt {
            root /usr/share/nginx/html;
            access_log off;
            log_not_found off;
        }

        location = /sitemap.xml {
            root /usr/share/nginx/html;
            access_log off;
            log_not_found off;
        }

        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ /index.html;
        }

        location /api {
            rewrite ^/api/(.*)$ /$1 break;
            proxy_pass http://backend_prod:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }

    server {
        listen 443 ssl;
        server_name tkremont58.ru;

        ssl_certificate     /etc/letsencrypt/live/tkremont58.ru/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/tkremont58.ru/privkey.pem;

        location = /robots.txt {
            root /usr/share/nginx/html;
            access_log off;
            log_not_found off;
        }

        location = /sitemap.xml {
            root /usr/share/nginx/html;
            access_log off;
            log_not_found off;
        }

        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ /index.html;
        }

        location /api {
                rewrite ^/api/(.*)$ /$1 break;
                proxy_pass http://backend_prod:8080;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
        }
    }
}