name: Deploy Fullstack

on:
  workflow_dispatch:
    inputs:
      tags:
        description: "Tag which should be deployed (e.g., v0.0.1)"
        required: true
        type: string

env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tags }}

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      - name: Add server to known hosts
        run: |
          mkdir -p ~/.ssh
          RAW_HOST="${{ secrets.SERVER_HOST }}"
          CLEAN_HOST=$(echo "$RAW_HOST" | sed 's/.*@//; s/:.*//')
          
          echo "Scanning host: $CLEAN_HOST"
          ssh-keyscan -H "$CLEAN_HOST" >> ~/.ssh/known_hosts 2>/dev/null || {
            echo "⚠️ ssh-keyscan failed, but continuing (first connection will ask for fingerprint)"
          }

      - name: Setup Docker & Compose on server
        env:
          HOST: ${{ secrets.SERVER_HOST }}
        run: |
          ssh -o StrictHostKeyChecking=no $HOST '
            set -e
            echo  "[INFO]: Setting up Docker & Compose"
          
            if command -v docker &> /dev/null && docker info &> /dev/null; then
              echo "[INFO]: Docker already installed"
            else
              echo "[INFO]: Installing Docker"
              curl -fsSL https://get.docker.com | sh
              systemctl enable docker
              systemctl start docker
            fi
          
            echo "[INFO]: Setting up Compose V2 Plugin"
            if docker compose version &> /dev/null; then
              echo "[INFO]: Compose V2 Plugin already installed"
            else
              echo "[INFO]: Installing Compose V2 Plugin"
              apt-get update -y
              apt-get install -y docker-compose
            fi

            echo  "[INFO]: Setting up Docker Network"
            docker network create monsieur-kotov-system || true
          
            echo "[INFO]: Docker is READY. Go next..."
          '

      - name: Generate .env file on server
        env:
          HOST: ${{ secrets.SERVER_HOST }}
          DEPLOY_DIR: /root/apps/ip_kotov
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          SSL_MODE: ${{ secrets.SSL_MODE }}
        run: |
          ssh $HOST "mkdir -p $DEPLOY_DIR"
          ssh $HOST "cat > $DEPLOY_DIR/.env" <<EOF
DB_USER=kotov_admin
DB_PASSWORD=$DB_PASSWORD
DB_NAME=ip_kotov_db
DB_HOST=db_postgres_prod
DB_PORT=5432
SSL_MODE=$SSL_MODE
APP_ENV=prod
VITE_API_URL=/api
EOF
          
      - name: Sync files to server
        env:
          HOST: ${{ secrets.SERVER_HOST }}
          DEPLOY_DIR: /root/apps/ip_kotov
        run: |
          rsync -avz --delete \
            -e "ssh" \
            --exclude='.git' \
            --exclude='.env' \
            --exclude='.gitignore' \
            --exclude='.github' \
            --exclude='deploy.yaml' \
            --exclude='.idea' \
            --exclude='.vscode' \
            --exclude='node_modules' \
            --exclude='.env.local' \
            --exclude='.env.example' \
            --exclude='.env.prod' \
            --exclude='.env.prod.local' \
            ./ $HOST:$DEPLOY_DIR/

      - name: Deploy fullstack application
        env:
          HOST: ${{ secrets.SERVER_HOST }}
          DEPLOY_DIR: /root/apps/ip_kotov
        run: |
          ssh -o StrictHostKeyChecking=no "$HOST" bash -s <<'REMOTESSH'
            set -e
            cd $DEPLOY_DIR
          
            echo "[INFO]: Stopping & Removing old containers"
            docker compose --profile prod --file docker-compose.yaml --env-file .env down --volumes
          
            echo "[INFO]: Starting new containers"
            docker compose --profile prod --file docker-compose.yaml --env-file .env up --build -d --remove-orphans
          
            echo "[INFO]: Waiting for containers to start"
            sleep 20
          
            echo "[INFO]: Checking containers status"
            docker ps
          
            echo "[WARN]: Not have healthchecking"
          
            echo 'Cleaning dangling images...'
            docker image prune -f || true
          
            echo 'Deployment successful!'
          REMOTESSH
